
// question
export const RECEIVE_QUESTION_STATUS = 'RECEIVE_QUESTION_STATUS'
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION'
export const RECEIVE_QUESTION_LEVELS = 'RECEIVE_QUESTION_LEVELS'
export const RECEIVE_QUESTION_CATEGORIES = 'RECEIVE_QUESTION_CATEGORIES'

// project
export const RECEIVE_CREATED_PROJECTS = 'RECEIVE_CREATED_PROJECTS'
export const RECEIVE_CREATED_PROJECTS_LOADING = 'RECEIVE_CREATED_PROJECTS_LOADING'
export const RECEIVE_PROJECT_BGS = 'RECEIVE_PROJECT_BGS'

//user
export const RECEIVE_USER = 'RECEIVE_USER'
